heat_template_version: rocky

description: >
  Logging configuration for containerized OpenDaylight API service
outputs:
  config_settings:
    description: Extra hieradata needed to log to files in the host.
    value: null
  docker_config:
    description: Extra containers needed for logging to files in the host.
    value:
      step_1: {}
  volumes:
    description: The volumes needed to log to files in the host.
    value:
      - /var/log/containers/opendaylight/karaf/logs:/opt/opendaylight/data/log
  host_prep_tasks:
    description: Extra ansible tasks needed for logging to files in the host.
    value:
      - name: create persistent logs directory
        file:
          path: "{{ item }}"
          state: directory
        with_items:
          - /var/log/containers/opendaylight/karaf/logs
          - /var/log/opendaylight
      - name: opendaylight logs readme
        copy:
          dest: /var/log/opendaylight/readme.txt
          content: |
            Logs from OpenDaylight container can be found at /var/log/containers/opendaylight/karaf/logs/karaf.log
        ignore_errors: true