heat_template_version: rocky

description: >
  OpenStack containerized Tempest

parameters:
  DockerTempestImage:
    description: image
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  UpgradeRemoveUnusedPackages:
    default: false
    description: Remove package if the service is being disabled during upgrade
    type: boolean

outputs:
  role_data:
    description: Role data for the tempest service
    value:
      # It just adds a fake tempest service so that it will be
      # available on undercloud.
      service_name: tempest
      docker_config:
        step_2:
          tempest_init_logs:
            image: &tempest_image {get_param: DockerTempestImage}
            privileged: false
            user: root
            volumes:
              - /var/log/containers/tempest:/var/log/tempest
            command: ['/bin/bash', '-c', 'chown -R tempest:tempest /var/log/tempest']
      host_prep_tasks:
        - name: create persistent logs directory
          file:
            path: "{{ item }}"
            state: directory
          with_items:
            - /var/log/containers/tempest
            - /var/log/tempest
        - name: Tempest logs readme
          copy:
            dest: /var/log/tempest/readme.txt
            content: |
              Log files from tempest containers can be found under
              /var/log/containers/tempest.
          ignore_errors: true
      puppet_config:
        config_volume: ''
        step_config: ''
        config_image: {get_param: DockerTempestImage}
      config_settings: {}
